### ISSUE TITLE
Armor setjes

### ISSUE THREAD

**Issue by Hen3Games** [Hen3Games/Prison-RP-TP#3]
Voor de Guard, Prisoner, Warden, Riot Guard en Head Guard ontbreken

**Comment by Hen3Games** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Armor setjes](https://trello.com/c/YzknoXnz/18-armor-setjes)

**Comment by RGerrits07** [comment]
Ook voor arts

**Comment by Hen3Games** [comment]
Wordt toegevoegd in update v1.0
